# Generated by Django 5.2.7 on 2025-10-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professionals/')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='professional',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.professional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='professionals',
            field=models.ManyToManyField(related_name='services', to='services.professional'),
        ),
    ]
