# Generated by Django 5.2.7 on 2025-10-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_booking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='morada',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
