# Generated by Django 5.2.7 on 2025-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='photo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
